import { Type, type JsonTypeBuilder } from '@sinclair/typebox'

// Limit to just types supported by JSON Schema
const JsonTypes: JsonTypeBuilder = {
  Any: Type.Any,
  Array: Type.Array,
  Boolean: Type.Boolean,
  Capitalize: Type.Capitalize,
  Composite: Type.Composite,
  Const: Type.Const,
  Enum: Type.Enum,
  Exclude: Type.Exclude,
  Extends: Type.Extends,
  Extract: Type.Extract,
  Index: Type.Index,
  Integer: Type.Integer,
  Intersect: Type.Intersect,
  KeyOf: Type.KeyOf,
  Literal: Type.Literal,
  Lowercase: Type.Lowercase,
  Module: Type.Module,
  Mapped: Type.Mapped,
  Never: Type.Never,
  Not: Type.Not,
  Null: Type.Null,
  Number: Type.Number,
  Object: Type.Object,
  Omit: Type.Omit,
  Optional: Type.Optional,
  Partial: Type.Partial,
  Pick: Type.Pick,
  Readonly: Type.Readonly,
  ReadonlyOptional: Type.ReadonlyOptional,
  Record: Type.Record,
  Recursive: Type.Recursive,
  Required: Type.Required,
  Rest: Type.Rest,
  Ref: Type.Ref,
  String: Type.String,
  TemplateLiteral: Type.TemplateLiteral,
  Transform: Type.Transform,
  Tuple: Type.Tuple,
  Uncapitalize: Type.Uncapitalize,
  Union: Type.Union,
  Unknown: Type.Unknown,
  Unsafe: Type.Unsafe,
  Uppercase: Type.Uppercase,
}

export default JsonTypes
